name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  source-checkout:
    name: Source Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: source-checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Pytest
        run: pytest --maxfail=5 --disable-warnings --tb=short

  vulnerability-scanning:
    name: Vulnerability Scanning
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r . -ll

  build-and-store-artifacts:
    name: Build Project and Store Artifacts
    runs-on: ubuntu-latest
    needs: vulnerability-scanning
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: |
          python setup.py sdist bdist_wheel
          mkdir -p build_output
          mv dist/* build_output/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: calculator-artifacts
          path: build_output/

  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: build-and-store-artifacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate deployment
        run: echo "Deploying application..."
